### PR TITLE
Configurable Fill Alpha (Radar Chart)

### PR DESCRIPTION
**Pull request by dphaldes**

### CODE REVIEW

**Comment by intkhabahmed** [comment]
@luiq54 please change the target branch to **release-v0.4.0**

**Comment by dphaldes** [comment]
I updated it!

**Comment by intkhabahmed** [comment]
I see you have merged the release branch with your branch, I was hoping you could rebase instead of merge as it has now created a new commit. Try creating a new branch from release branch and cherry-pick your commit and then force push, it will remove the extra commit.

**Comment by intkhabahmed** [comment]
There is a conflict in radar_chart_painter file, fix that please

**Comment by dphaldes** [comment]
I am not able to figure out cherrypicking. I will close this PR and open another one properly.

**Pull request closed without merging**
