### PR TITLE
add showPoint optional parameter in RadarChart

### PR DESCRIPTION
**Pull request by taz1208**
Here is example image :)
image

### CODE REVIEW

**Comment by intkhabahmed** [comment]
are you using dev channel?

**Comment by taz1208** [comment]
Oops, Sorry I using master channel

**Comment by taz1208** [comment]
You mean dev channel is beta channel?

**Comment by taz1208** [comment]
I will close this and I will make another pull request.

I apologize for make many trash request.

**Comment by intkhabahmed** [comment]
> You mean dev channel is beta channel?

yes, kind of

**Comment by intkhabahmed** [comment]
Always use **stable** channel

**Comment by taz1208** [comment]
Should I use stable channel?
Okay I will change this.
I am sorry to have bothered you.

**Comment by intkhabahmed** [comment]
> Should I use stable channel?
> Okay I will change this.
> I am sorry to have bothered you.

yes, please use stable channel. Also some versions in the pubspec file is still having the dev channel dependencies. Please change that.
Also, add a radius parameter for the dot so that it can be customised

**Comment by taz1208** [comment]
I added 'pointRadius'
But I'm not sure where is wrong in pubspec

I tried like this
1.Change to stable channel
2.Remove pubspec.lock
3.Command 'pub get' in terminnal

Please teach me

**Comment by intkhabahmed** [comment]
Do one thing. create a new branch from the master branch. move your changes to that branch and then commit.

**Comment by taz1208** [comment]
The master branch mean your's?
Are you saying to fork again?

**Comment by intkhabahmed** [comment]
> The master branch mean your's?
> Are you saying to fork again?

Don't fork again. You might have created branch from your local master, right? If you directly did changes in master branch, then you need to stash your changes and checkout a new master from the origin or fork again

**Pull request closed without merging**
