### PR TITLE
Configurable Fill Alpha

### PR DESCRIPTION
**Pull request by dphaldes**

### CODE REVIEW

**Comment by dphaldes** [comment]
I hope I did it properly this time.

**Comment by intkhabahmed** [comment]
yes, it's right this time. You need to do one more thing, add this in the readme file for documentation

**Comment by dphaldes** [comment]
Please tell if this was proper! 😄

**Comment by intkhabahmed** [comment]
yes, its proper, but no need to force push every time, earlier I said to force push to remove the unwanted merge commit which was introduced. But if you are doing any new required changes, then you can simply commit and normally push

**Review by intkhabahmed — APPROVED** [review]
All looks good to me

**Pull request merged**
